# Generated by Django 5.0.6 on 2024-06-05 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('year_of_study', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LecturerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.lecturers')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.lecturers')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.lecturers')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.lecturerrating')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.reviews')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
        migrations.AddField(
            model_name='lecturers',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students'),
        ),
    ]
