# Generated by Django 5.0.6 on 2024-06-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lecturers',
            new_name='Lecturer',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='ReviewDetails',
            new_name='ReviewDetail',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
