# Generated by Django 5.0.6 on 2024-06-05 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_lecturers_lecturer_rename_reviews_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewdetail',
            old_name='Student',
            new_name='studentName',
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
