# Generated by Django 5.0.6 on 2024-06-05 14:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_student_reviewdetail_studentname_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdetail',
            name='date',
        ),
        migrations.AddField(
            model_name='reviewdetail',
            name='date_reviewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reviewdetail',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_details', to='students.review'),
        ),
    ]
