# Generated by Django 5.0.6 on 2024-06-05 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_reviewdetail_date_reviewdetail_date_reviewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdetail',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.review'),
        ),
        migrations.DeleteModel(
            name='LecturerRating',
        ),
    ]
