# Generated by Django 5.0.6 on 2024-06-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
    ]
