# Generated by Django 5.0.6 on 2024-06-09 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdetail',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='reviewdetail',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewdetail',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='reviewdetail',
            name='studentName',
        ),
        migrations.CreateModel(
            name='Review_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('review_date', models.DateField()),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.lecturer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewDetail',
        ),
    ]
