# Generated by Django 5.0.6 on 2024-06-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_rename_lecturer_review_detail_lecturername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_detail',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='review_detail',
            name='lecturername',
        ),
        migrations.RemoveField(
            model_name='review_detail',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review_detail',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='review_detail',
            name='student',
        ),
    ]
