# Generated by Django 5.0.6 on 2024-06-09 21:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_review_detail_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_detail',
            name='comment',
            field=models.TextField(default='nice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review_detail',
            name='lecturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.lecturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review_detail',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review_detail',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review_detail',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
            preserve_default=False,
        ),
    ]
