# Generated by Django 5.0.6 on 2024-06-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_rename_course_student_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=2222, max_length=100),
            preserve_default=False,
        ),
    ]
