# Generated by Django 5.0.6 on 2024-06-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='students',
        ),
    ]
